---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring-production
  labels:
    name: monitoring-production

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: monitoring-production

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring-production
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
      external_labels:
        monitor: 'devops-toolkit'
        environment: 'production'

    scrape_configs:
      # Prometheus itself
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
            labels:
              service: 'prometheus'

      # Node Exporter (System Metrics - CPU, RAM, Disk, Network)
      - job_name: 'node-exporter'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            action: keep
            regex: node-exporter
          - source_labels: [__meta_kubernetes_pod_ip]
            target_label: __address__
            replacement: $1:9100
          - source_labels: [__meta_kubernetes_pod_node_name]
            target_label: instance

      # cAdvisor (Docker Container Metrics)
      - job_name: 'cadvisor'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            action: keep
            regex: cadvisor
          - source_labels: [__meta_kubernetes_pod_ip]
            target_label: __address__
            replacement: $1:8080
          - source_labels: [__meta_kubernetes_pod_node_name]
            target_label: instance

      # Kubernetes Pods (General pod discovery for annotated pods)
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
  namespace: monitoring-production
data:
  dashboard.yml: |
    apiVersion: 1
    providers:
      - name: 'DevOps Observatory'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /etc/grafana/provisioning/dashboards

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring-production
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus.monitoring-production.svc.cluster.local:9090
        isDefault: true
        editable: true

---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-credentials
  namespace: monitoring-production
type: Opaque
data:
  admin-password: ZDViMDUyNTYtY2Y1My00ODRhLTk4N2ItMzI5Y2I1ZTQyMzJi
  admin-user: YWRtaW4tZGV2b3BzdG9vbGtpdA==

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
  namespace: monitoring-production
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: local-path
  volumeMode: Filesystem

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: monitoring-production
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
  volumeMode: Filesystem

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: monitoring-production
  labels:
    app: devops-toolkit
    component: monitoring
spec:
  type: ClusterIP
  selector:
    app: devops-toolkit
    component: prometheus
  ports:
  - name: http
    port: 9090
    protocol: TCP
    targetPort: 9090

---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring-production
  labels:
    app: devops-toolkit
    component: grafana
spec:
  type: ClusterIP
  selector:
    app: devops-toolkit
    component: grafana
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: monitoring-production
  labels:
    app: devops-toolkit
    component: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-toolkit
      component: prometheus
  template:
    metadata:
      labels:
        app: devops-toolkit
        component: prometheus
    spec:
      serviceAccountName: prometheus
      containers:
      - name: prometheus
        image: prom/prometheus:latest
        imagePullPolicy: Always
        args:
        - --config.file=/etc/prometheus/prometheus.yml
        - --storage.tsdb.path=/prometheus
        - --web.console.libraries=/etc/prometheus/console_libraries
        - --web.console.templates=/etc/prometheus/consoles
        - --web.enable-lifecycle
        ports:
        - containerPort: 9090
          name: http
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: 200m
            memory: 512Mi
        volumeMounts:
        - mountPath: /etc/prometheus
          name: prometheus-config
        - mountPath: /prometheus
          name: prometheus-data
      volumes:
      - name: prometheus-config
        configMap:
          name: prometheus-config
      - name: prometheus-data
        persistentVolumeClaim:
          claimName: prometheus-pvc

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring-production
  labels:
    app: devops-toolkit
    component: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-toolkit
      component: grafana
  template:
    metadata:
      labels:
        app: devops-toolkit
        component: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest
        imagePullPolicy: Always
        env:
        - name: GF_SECURITY_ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: grafana-credentials
              key: admin-user
        - name: GF_SECURITY_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: grafana-credentials
              key: admin-password
        - name: GF_INSTALL_PLUGINS
          value: grafana-clock-panel,grafana-simple-json-datasource,grafana-piechart-panel
        ports:
        - containerPort: 3000
          name: http
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 30
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
        volumeMounts:
        - mountPath: /var/lib/grafana
          name: grafana-storage
        - mountPath: /etc/grafana/provisioning/dashboards
          name: grafana-dashboards
        - mountPath: /etc/grafana/provisioning/datasources
          name: grafana-datasources
      volumes:
      - name: grafana-storage
        persistentVolumeClaim:
          claimName: grafana-pvc
      - name: grafana-dashboards
        configMap:
          name: grafana-dashboards
      - name: grafana-datasources
        configMap:
          name: grafana-datasources

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: grafana
  namespace: monitoring-production
spec:
  parentRefs:
  - name: global-gateway
    namespace: nginx-gateway
    sectionName: grafana
  hostnames:
  - grafana.devops-toolkit.dremer10.com
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: grafana
      port: 3000
