---
apiVersion: v1
kind: Namespace
metadata:
  name: pub-site-prod
  labels:
    name: pub-site-prod

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pub-site-grafana-links
  namespace: pub-site-prod
data:
  grafana.json: |
    {
      "production": "https://grafana.devops-toolkit.dremer10.com/public-dashboards/7ac9ca2bc8ee46d58e2daf666ec5f795",
      "staging": "https://grafana-staging.devops-toolkit.dremer10.com/public-dashboards/a6c75aece6e0437a993bb1ca63ab5643"
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pub-site
  namespace: pub-site-prod
  labels:
    app: pub-site
    environment: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pub-site
      environment: production
  template:
    metadata:
      labels:
        app: pub-site
        environment: production
    spec:
      containers:
      - name: pub-site
        image: dremer10/pub-site:${PUB_SITE_IMAGE_TAG}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
        - name: grafana-links
          mountPath: /usr/share/nginx/html/config/grafana.json
          subPath: grafana.json
          readOnly: true
        resources:
          requests:
            memory: "16Mi"
            cpu: "10m"
          limits:
            memory: "32Mi"
            cpu: "50m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: grafana-links
        configMap:
          name: pub-site-grafana-links

---
apiVersion: v1
kind: Service
metadata:
  name: pub-site
  namespace: pub-site-prod
  labels:
    app: pub-site
    environment: production
spec:
  type: ClusterIP
  selector:
    app: pub-site
    environment: production
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: pub-site
  namespace: pub-site-prod
spec:
  parentRefs:
  - name: global-gateway
    namespace: nginx-gateway
    sectionName: pub-site-prod
  hostnames:
  - info.dremer10.com
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: pub-site
      port: 80
